/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SapatosRouteImport } from './routes/sapatos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PromocaoRouteImport } from './routes/promocao'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CintosRouteImport } from './routes/cintos'
import { Route as BolsasRouteImport } from './routes/bolsas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminPaginasRouteImport } from './routes/admin.paginas'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin.pedidos.index'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'

const SapatosRoute = SapatosRouteImport.update({
  id: '/sapatos',
  path: '/sapatos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocaoRoute = PromocaoRouteImport.update({
  id: '/promocao',
  path: '/promocao',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CintosRoute = CintosRouteImport.update({
  id: '/cintos',
  path: '/cintos',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsasRoute = BolsasRouteImport.update({
  id: '/bolsas',
  path: '/bolsas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasRoute = AdminPaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bolsas': typeof BolsasRoute
  '/cintos': typeof CintosRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/promocao': typeof PromocaoRoute
  '/register': typeof RegisterRoute
  '/sapatos': typeof SapatosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bolsas': typeof BolsasRoute
  '/cintos': typeof CintosRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/promocao': typeof PromocaoRoute
  '/register': typeof RegisterRoute
  '/sapatos': typeof SapatosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bolsas': typeof BolsasRoute
  '/cintos': typeof CintosRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/promocao': typeof PromocaoRoute
  '/register': typeof RegisterRoute
  '/sapatos': typeof SapatosRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bolsas'
    | '/cintos'
    | '/login'
    | '/novidades'
    | '/promocao'
    | '/register'
    | '/sapatos'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/editor'
    | '/admin/estoque'
    | '/admin/paginas'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/clientes/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bolsas'
    | '/cintos'
    | '/login'
    | '/novidades'
    | '/promocao'
    | '/register'
    | '/sapatos'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/editor'
    | '/admin/estoque'
    | '/admin/paginas'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/clientes'
    | '/admin/pedidos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bolsas'
    | '/cintos'
    | '/login'
    | '/novidades'
    | '/promocao'
    | '/register'
    | '/sapatos'
    | '/admin/banners'
    | '/admin/configuracoes'
    | '/admin/editor'
    | '/admin/estoque'
    | '/admin/paginas'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/clientes/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BolsasRoute: typeof BolsasRoute
  CintosRoute: typeof CintosRoute
  LoginRoute: typeof LoginRoute
  NovidadesRoute: typeof NovidadesRoute
  PromocaoRoute: typeof PromocaoRoute
  RegisterRoute: typeof RegisterRoute
  SapatosRoute: typeof SapatosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sapatos': {
      id: '/sapatos'
      path: '/sapatos'
      fullPath: '/sapatos'
      preLoaderRoute: typeof SapatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocao': {
      id: '/promocao'
      path: '/promocao'
      fullPath: '/promocao'
      preLoaderRoute: typeof PromocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cintos': {
      id: '/cintos'
      path: '/cintos'
      fullPath: '/cintos'
      preLoaderRoute: typeof CintosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsas': {
      id: '/bolsas'
      path: '/bolsas'
      fullPath: '/bolsas'
      preLoaderRoute: typeof BolsasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas': {
      id: '/admin/paginas'
      path: '/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AdminPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEditorRoute: typeof AdminEditorRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminPaginasRoute: typeof AdminPaginasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIdRoute: typeof AdminClientesIdRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEditorRoute: AdminEditorRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminPaginasRoute: AdminPaginasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIdRoute: AdminClientesIdRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BolsasRoute: BolsasRoute,
  CintosRoute: CintosRoute,
  LoginRoute: LoginRoute,
  NovidadesRoute: NovidadesRoute,
  PromocaoRoute: PromocaoRoute,
  RegisterRoute: RegisterRoute,
  SapatosRoute: SapatosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
