/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PromocaoRouteImport } from './routes/promocao'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminEditorRouteImport } from './routes/admin.editor'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin.pedidos.index'
import { Route as AdminPaginasIndexRouteImport } from './routes/admin.paginas.index'
import { Route as AdminConfiguracoesIndexRouteImport } from './routes/admin.configuracoes.index'
import { Route as AdminColecoesIndexRouteImport } from './routes/admin.colecoes.index'
import { Route as AdminClientesIndexRouteImport } from './routes/admin.clientes.index'
import { Route as AdminCategoriasIndexRouteImport } from './routes/admin.categorias.index'
import { Route as AdminBannersIndexRouteImport } from './routes/admin.banners.index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin.produtos.novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin.produtos.$id'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as AdminPaginasIdRouteImport } from './routes/admin.paginas.$id'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocaoRoute = PromocaoRouteImport.update({
  id: '/promocao',
  path: '/promocao',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorRoute = AdminEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasIndexRoute = AdminPaginasIndexRouteImport.update({
  id: '/paginas/',
  path: '/paginas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesIndexRoute = AdminConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminColecoesIndexRoute = AdminColecoesIndexRouteImport.update({
  id: '/colecoes/',
  path: '/colecoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIndexRoute = AdminClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasIndexRoute = AdminCategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersIndexRoute = AdminBannersIndexRouteImport.update({
  id: '/banners/',
  path: '/banners/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasIdRoute = AdminPaginasIdRouteImport.update({
  id: '/paginas/$id',
  path: '/paginas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/promocao': typeof PromocaoRoute
  '/register': typeof RegisterRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/c/$slug': typeof CSlugRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/paginas/$id': typeof AdminPaginasIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/categorias/': typeof AdminCategoriasIndexRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/colecoes/': typeof AdminColecoesIndexRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/paginas/': typeof AdminPaginasIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/promocao': typeof PromocaoRoute
  '/register': typeof RegisterRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/c/$slug': typeof CSlugRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/paginas/$id': typeof AdminPaginasIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/banners': typeof AdminBannersIndexRoute
  '/admin/categorias': typeof AdminCategoriasIndexRoute
  '/admin/clientes': typeof AdminClientesIndexRoute
  '/admin/colecoes': typeof AdminColecoesIndexRoute
  '/admin/configuracoes': typeof AdminConfiguracoesIndexRoute
  '/admin/paginas': typeof AdminPaginasIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/novidades': typeof NovidadesRoute
  '/promocao': typeof PromocaoRoute
  '/register': typeof RegisterRoute
  '/admin/editor': typeof AdminEditorRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/c/$slug': typeof CSlugRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRoute
  '/admin/paginas/$id': typeof AdminPaginasIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/banners/': typeof AdminBannersIndexRoute
  '/admin/categorias/': typeof AdminCategoriasIndexRoute
  '/admin/clientes/': typeof AdminClientesIndexRoute
  '/admin/colecoes/': typeof AdminColecoesIndexRoute
  '/admin/configuracoes/': typeof AdminConfiguracoesIndexRoute
  '/admin/paginas/': typeof AdminPaginasIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/novidades'
    | '/promocao'
    | '/register'
    | '/admin/editor'
    | '/admin/estoque'
    | '/c/$slug'
    | '/colecao/$slug'
    | '/p/$slug'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/paginas/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/banners/'
    | '/admin/categorias/'
    | '/admin/clientes/'
    | '/admin/colecoes/'
    | '/admin/configuracoes/'
    | '/admin/paginas/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/novidades'
    | '/promocao'
    | '/register'
    | '/admin/editor'
    | '/admin/estoque'
    | '/c/$slug'
    | '/colecao/$slug'
    | '/p/$slug'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/paginas/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/colecoes'
    | '/admin/configuracoes'
    | '/admin/paginas'
    | '/admin/pedidos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/novidades'
    | '/promocao'
    | '/register'
    | '/admin/editor'
    | '/admin/estoque'
    | '/c/$slug'
    | '/colecao/$slug'
    | '/p/$slug'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/paginas/$id'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/banners/'
    | '/admin/categorias/'
    | '/admin/clientes/'
    | '/admin/colecoes/'
    | '/admin/configuracoes/'
    | '/admin/paginas/'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovidadesRoute: typeof NovidadesRoute
  PromocaoRoute: typeof PromocaoRoute
  RegisterRoute: typeof RegisterRoute
  CSlugRoute: typeof CSlugRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocao': {
      id: '/promocao'
      path: '/promocao'
      fullPath: '/promocao'
      preLoaderRoute: typeof PromocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas/': {
      id: '/admin/paginas/'
      path: '/paginas'
      fullPath: '/admin/paginas/'
      preLoaderRoute: typeof AdminPaginasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes/': {
      id: '/admin/configuracoes/'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes/'
      preLoaderRoute: typeof AdminConfiguracoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/colecoes/': {
      id: '/admin/colecoes/'
      path: '/colecoes'
      fullPath: '/admin/colecoes/'
      preLoaderRoute: typeof AdminColecoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/': {
      id: '/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AdminClientesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias/': {
      id: '/admin/categorias/'
      path: '/categorias'
      fullPath: '/admin/categorias/'
      preLoaderRoute: typeof AdminCategoriasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners/': {
      id: '/admin/banners/'
      path: '/banners'
      fullPath: '/admin/banners/'
      preLoaderRoute: typeof AdminBannersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas/$id': {
      id: '/admin/paginas/$id'
      path: '/paginas/$id'
      fullPath: '/admin/paginas/$id'
      preLoaderRoute: typeof AdminPaginasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEditorRoute: typeof AdminEditorRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientesIdRoute: typeof AdminClientesIdRoute
  AdminPaginasIdRoute: typeof AdminPaginasIdRoute
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminBannersIndexRoute: typeof AdminBannersIndexRoute
  AdminCategoriasIndexRoute: typeof AdminCategoriasIndexRoute
  AdminClientesIndexRoute: typeof AdminClientesIndexRoute
  AdminColecoesIndexRoute: typeof AdminColecoesIndexRoute
  AdminConfiguracoesIndexRoute: typeof AdminConfiguracoesIndexRoute
  AdminPaginasIndexRoute: typeof AdminPaginasIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEditorRoute: AdminEditorRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientesIdRoute: AdminClientesIdRoute,
  AdminPaginasIdRoute: AdminPaginasIdRoute,
  AdminPedidosIdRoute: AdminPedidosIdRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminBannersIndexRoute: AdminBannersIndexRoute,
  AdminCategoriasIndexRoute: AdminCategoriasIndexRoute,
  AdminClientesIndexRoute: AdminClientesIndexRoute,
  AdminColecoesIndexRoute: AdminColecoesIndexRoute,
  AdminConfiguracoesIndexRoute: AdminConfiguracoesIndexRoute,
  AdminPaginasIndexRoute: AdminPaginasIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  NovidadesRoute: NovidadesRoute,
  PromocaoRoute: PromocaoRoute,
  RegisterRoute: RegisterRoute,
  CSlugRoute: CSlugRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
